/**
 * Node.js Middleware Chain Template
 *
 * Generates a middleware chain setup file that applies all configured
 * middleware in the correct order.
 *
 * @module cli/generators/node-handlers/middleware-chain-template
 * @category CLI
 */

import type {
  SchemockConfig,
  MiddlewareConfig,
  AnalyzedMiddleware,
  AuthMiddlewareConfig,
  RateLimitMiddlewareConfig,
  CacheMiddlewareConfig,
  LoggerMiddlewareConfig,
} from '../../types';

/**
 * Middleware ordering constants
 */
const DEFAULT_MIDDLEWARE_ORDER = [
  'auth',
  'rateLimit',
  'logger',
  'context',
  'rls',
  'cache',
  'validation',
];

/**
 * Generate the middleware chain setup file
 *
 * @param config - Schemock config with middleware settings
 * @param customMiddleware - Analyzed custom middleware definitions
 * @returns Generated middleware chain code
 */
export function generateMiddlewareChain(
  config: SchemockConfig,
  customMiddleware: AnalyzedMiddleware[] = []
): string {
  const middleware = config.middleware ?? {};
  const enabledMiddleware = getEnabledMiddleware(middleware);
  const orderedMiddleware = orderMiddleware(enabledMiddleware, middleware.chain, customMiddleware);

  const lines: string[] = [
    '// GENERATED BY SCHEMOCK - DO NOT EDIT',
    '',
    "import type { Router, Request, Response, NextFunction } from 'express';",
    '',
  ];

  // Generate imports for each middleware
  const imports = generateMiddlewareImports(orderedMiddleware, customMiddleware);
  lines.push(...imports);

  lines.push('');
  lines.push('/**');
  lines.push(' * Middleware handler type');
  lines.push(' */');
  lines.push('export type MiddlewareHandler = (');
  lines.push('  req: Request,');
  lines.push('  res: Response,');
  lines.push('  next: NextFunction');
  lines.push(') => void | Promise<void>;');
  lines.push('');

  lines.push('/**');
  lines.push(' * Apply all configured middleware to a router');
  lines.push(' * Middleware is applied in the following order:');
  for (const name of orderedMiddleware) {
    lines.push(` *   - ${name}`);
  }
  lines.push(' */');
  lines.push('export function applyMiddleware(router: Router): void {');

  if (orderedMiddleware.length === 0) {
    lines.push('  // No middleware configured');
  } else {
    for (const name of orderedMiddleware) {
      const handlerName = getMiddlewareHandlerName(name);
      lines.push(`  router.use(${handlerName});`);
    }
  }

  lines.push('}');
  lines.push('');

  // Export individual middleware for selective use
  lines.push('/**');
  lines.push(' * Export individual middleware handlers for selective use');
  lines.push(' */');
  lines.push('export const middleware = {');
  for (const name of orderedMiddleware) {
    const handlerName = getMiddlewareHandlerName(name);
    lines.push(`  ${name}: ${handlerName},`);
  }
  lines.push('} as const;');
  lines.push('');

  // Export the ordered list
  lines.push('/**');
  lines.push(' * Middleware execution order');
  lines.push(' */');
  lines.push(`export const middlewareOrder = ${JSON.stringify(orderedMiddleware)} as const;`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Get list of enabled middleware from config
 */
function getEnabledMiddleware(config: MiddlewareConfig): string[] {
  const enabled: string[] = [];

  if (config.auth) enabled.push('auth');
  if (config.rateLimit) enabled.push('rateLimit');
  if (config.logger) enabled.push('logger');
  if (config.context) enabled.push('context');
  if (config.rls) enabled.push('rls');
  if (config.cache) enabled.push('cache');
  if (config.validation) enabled.push('validation');

  return enabled;
}

/**
 * Order middleware based on config.chain or default order
 */
function orderMiddleware(
  enabled: string[],
  customOrder?: string[],
  customMiddleware: AnalyzedMiddleware[] = []
): string[] {
  // Get custom middleware names categorized by order
  const earlyCustom = customMiddleware.filter((m) => m.order === 'early').map((m) => m.name);
  const normalCustom = customMiddleware.filter((m) => m.order === 'normal').map((m) => m.name);
  const lateCustom = customMiddleware.filter((m) => m.order === 'late').map((m) => m.name);

  if (customOrder && customOrder.length > 0) {
    // Use custom order, but only include enabled middleware
    const allEnabled = new Set([...enabled, ...customMiddleware.map((m) => m.name)]);
    return customOrder.filter((name) => allEnabled.has(name));
  }

  // Use default order, inserting custom middleware at appropriate positions
  const ordered: string[] = [];

  // Early custom middleware first
  ordered.push(...earlyCustom.filter((n) => !enabled.includes(n)));

  // Built-in middleware in default order
  for (const name of DEFAULT_MIDDLEWARE_ORDER) {
    if (enabled.includes(name)) {
      ordered.push(name);
    }
  }

  // Normal custom middleware after built-in
  ordered.push(...normalCustom.filter((n) => !enabled.includes(n)));

  // Late custom middleware last
  ordered.push(...lateCustom.filter((n) => !enabled.includes(n)));

  return ordered;
}

/**
 * Generate import statements for middleware
 */
function generateMiddlewareImports(
  orderedMiddleware: string[],
  customMiddleware: AnalyzedMiddleware[]
): string[] {
  const lines: string[] = [];
  const customNames = new Set(customMiddleware.map((m) => m.name));

  // Built-in middleware imports
  const builtInImports: string[] = [];

  for (const name of orderedMiddleware) {
    if (!customNames.has(name)) {
      const handlerName = getMiddlewareHandlerName(name);
      builtInImports.push(handlerName);
    }
  }

  if (builtInImports.length > 0) {
    // Group imports by file
    const authImports = builtInImports.filter((n) => n === 'authMiddleware');
    const rateLimitImports = builtInImports.filter((n) => n === 'rateLimitMiddleware');
    const cacheImports = builtInImports.filter((n) => n === 'cacheMiddleware');
    const loggerImports = builtInImports.filter((n) => n === 'loggerMiddleware');
    const contextImports = builtInImports.filter((n) => n === 'contextMiddleware');
    const rlsImports = builtInImports.filter((n) => n === 'rlsMiddleware');
    const validationImports = builtInImports.filter((n) => n === 'validationMiddleware');

    if (authImports.length > 0) {
      lines.push("import { authMiddleware } from './auth';");
    }
    if (rateLimitImports.length > 0) {
      lines.push("import { rateLimitMiddleware } from './rate-limit';");
    }
    if (cacheImports.length > 0) {
      lines.push("import { cacheMiddleware } from './cache';");
    }
    if (loggerImports.length > 0) {
      lines.push("import { loggerMiddleware } from './logger';");
    }
    if (contextImports.length > 0) {
      lines.push("import { contextMiddleware } from './context';");
    }
    if (rlsImports.length > 0) {
      lines.push("import { rlsMiddleware } from './rls';");
    }
    if (validationImports.length > 0) {
      lines.push("import { validationMiddleware } from './validate';");
    }
  }

  // Custom middleware imports
  for (const mw of customMiddleware) {
    if (orderedMiddleware.includes(mw.name)) {
      const handlerName = `${mw.name}Middleware`;
      lines.push(`import { ${handlerName} } from './custom/${mw.name}';`);
    }
  }

  return lines;
}

/**
 * Get the handler function name for a middleware
 */
function getMiddlewareHandlerName(name: string): string {
  // Handle hyphenated names like 'rate-limit' -> 'rateLimitMiddleware'
  const camelCase = name.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
  return `${camelCase}Middleware`;
}

/**
 * Normalize middleware config to get the full config object
 */
export function normalizeAuthConfig(
  config: AuthMiddlewareConfig | boolean | undefined
): AuthMiddlewareConfig | undefined {
  if (!config) return undefined;
  if (config === true) {
    return { provider: 'jwt', required: true };
  }
  return config;
}

export function normalizeLoggerConfig(
  config: LoggerMiddlewareConfig | boolean | undefined
): LoggerMiddlewareConfig | undefined {
  if (!config) return undefined;
  if (config === true) {
    return { level: 'info' };
  }
  return config;
}

export function normalizeCacheConfig(
  config: CacheMiddlewareConfig | boolean | undefined
): CacheMiddlewareConfig | undefined {
  if (!config) return undefined;
  if (config === true) {
    return { ttl: 300000, operations: ['findOne', 'findMany'] };
  }
  return config;
}
