/**
 * Node.js Router Template
 *
 * Generates Express-compatible router that combines all entity handlers.
 *
 * @module cli/generators/node-handlers/router-template
 * @category CLI
 */

import type { AnalyzedSchema, GenerationTarget, SchemockConfig } from '../../types';

/**
 * Generate the main router file
 */
export function generateRouterFile(
  schemas: AnalyzedSchema[],
  target: GenerationTarget,
  config: SchemockConfig
): string {
  const hasAuth = target.middleware?.auth !== undefined;
  const apiPrefix = config.apiPrefix || '/api';

  const lines: string[] = [
    '// GENERATED BY SCHEMOCK - DO NOT EDIT',
    '',
    "import { Router, json, type Request, type Response, type NextFunction } from 'express';",
  ];

  // Import handlers
  for (const schema of schemas) {
    if (schema.isJunctionTable) continue;
    lines.push(`import * as ${schema.pluralName}Handlers from './handlers/${schema.pluralName}';`);
  }

  // Import auth middleware if configured
  if (hasAuth) {
    lines.push("import { authMiddleware } from './middleware/auth';");
  }

  lines.push('');
  lines.push('/**');
  lines.push(' * Create the API router with all entity routes');
  lines.push(' */');
  lines.push('export function createRouter(): Router {');
  lines.push('  const router = Router();');
  lines.push('');
  lines.push('  // Parse JSON bodies');
  lines.push('  router.use(json());');
  lines.push('');

  if (hasAuth) {
    lines.push('  // Apply auth middleware to all routes');
    lines.push('  router.use(authMiddleware);');
    lines.push('');
  }

  // Generate routes for each entity
  for (const schema of schemas) {
    if (schema.isJunctionTable) continue;

    lines.push(`  // ${schema.pascalName} routes`);
    lines.push(`  router.get('/${schema.pluralName}', ${schema.pluralName}Handlers.list);`);
    lines.push(`  router.get('/${schema.pluralName}/:id', ${schema.pluralName}Handlers.getOne);`);
    lines.push(`  router.post('/${schema.pluralName}', ${schema.pluralName}Handlers.create);`);
    lines.push(`  router.put('/${schema.pluralName}/:id', ${schema.pluralName}Handlers.update);`);
    lines.push(`  router.delete('/${schema.pluralName}/:id', ${schema.pluralName}Handlers.remove);`);
    lines.push('');
  }

  lines.push('  // Error handling middleware');
  lines.push('  router.use((err: Error, _req: Request, res: Response, _next: NextFunction) => {');
  lines.push("    console.error('API Error:', err);");
  lines.push("    res.status(500).json({ error: err.message || 'Internal server error' });");
  lines.push('  });');
  lines.push('');
  lines.push('  return router;');
  lines.push('}');
  lines.push('');

  // Create default router instance
  lines.push('/**');
  lines.push(' * Default router instance');
  lines.push(` * Mount at: app.use('${apiPrefix}', router)`);
  lines.push(' */');
  lines.push('export const router = createRouter();');
  lines.push('');

  // Add usage example
  lines.push('/**');
  lines.push(' * Usage example:');
  lines.push(' * ```');
  lines.push(" * import express from 'express';");
  lines.push(" * import { router } from './generated/node';");
  lines.push(' * ');
  lines.push(' * const app = express();');
  lines.push(` * app.use('${apiPrefix}', router);`);
  lines.push(' * app.listen(3000);');
  lines.push(' * ```');
  lines.push(' */');

  return lines.join('\n');
}

/**
 * Generate a standalone router for a single entity
 */
export function generateEntityRouter(
  schema: AnalyzedSchema,
  target: GenerationTarget
): string {
  const hasAuth = target.middleware?.auth !== undefined;

  const lines: string[] = [
    '// GENERATED BY SCHEMOCK - DO NOT EDIT',
    '',
    "import { Router } from 'express';",
    `import * as handlers from './handlers/${schema.pluralName}';`,
  ];

  if (hasAuth) {
    lines.push("import { authMiddleware } from './middleware/auth';");
  }

  lines.push('');
  lines.push(`export const ${schema.pluralName}Router = Router();`);
  lines.push('');

  if (hasAuth) {
    lines.push(`${schema.pluralName}Router.use(authMiddleware);`);
    lines.push('');
  }

  lines.push(`${schema.pluralName}Router.get('/', handlers.list);`);
  lines.push(`${schema.pluralName}Router.get('/:id', handlers.getOne);`);
  lines.push(`${schema.pluralName}Router.post('/', handlers.create);`);
  lines.push(`${schema.pluralName}Router.put('/:id', handlers.update);`);
  lines.push(`${schema.pluralName}Router.delete('/:id', handlers.remove);`);

  return lines.join('\n');
}
