/**
 * Mock seed utilities generator
 *
 * @module cli/generators/mock/seed
 * @category CLI
 */

import type { AnalyzedSchema, MockAdapterConfig } from '../../types';
import { CodeBuilder } from '../../utils/code-builder';

/**
 * Generate seed and reset utilities for mock database
 *
 * @param schemas - Analyzed schemas
 * @param config - Mock adapter configuration
 * @returns Generated TypeScript code
 */
export function generateSeed(schemas: AnalyzedSchema[], config: MockAdapterConfig): string {
  const code = new CodeBuilder();

  code.comment('GENERATED BY SCHEMOCK - DO NOT EDIT');
  code.line("import { db } from './db';");
  code.line();

  // Type for seed counts
  code.block('export interface SeedCounts {', () => {
    for (const schema of schemas) {
      if (schema.isJunctionTable) continue;
      code.line(`${schema.name}?: number;`);
    }
  });
  code.line();

  // Default counts
  code.block('const defaultCounts: Required<SeedCounts> = {', () => {
    for (const schema of schemas) {
      if (schema.isJunctionTable) continue;
      const count = config.seed?.[schema.name] ?? 10;
      code.line(`${schema.name}: ${count},`);
    }
  }, '};');
  code.line();

  // Helper to pick random item from array
  code.block('function pickRandom<T>(arr: T[]): T | undefined {', () => {
    code.line('if (arr.length === 0) return undefined;');
    code.line('return arr[Math.floor(Math.random() * arr.length)];');
  });
  code.line();

  // Seed function - creates relational data with valid foreign keys
  code.block('export function seed(counts: SeedCounts = {}): void {', () => {
    code.line('const merged = { ...defaultCounts, ...counts };');
    code.line();
    code.comment('Track created entity IDs for foreign key references');
    code.line('const ids: Record<string, string[]> = {};');
    code.line();

    // Generate in dependency order (schemas are already sorted)
    for (const schema of schemas) {
      if (schema.isJunctionTable) continue;

      // Find FK fields from belongsTo relations (these need valid parent IDs)
      const belongsToRels = schema.relations.filter(r => r.type === 'belongsTo');
      // Map: localField -> target entity name
      const fkFields = belongsToRels.map(r => ({
        fieldName: r.localField || r.foreignKey,
        target: r.target,
        nullable: schema.fields.find(f => f.name === (r.localField || r.foreignKey))?.nullable ?? false,
      }));

      code.line(`ids.${schema.name} = [];`);
      code.block(`for (let i = 0; i < merged.${schema.name}; i++) {`, () => {
        if (fkFields.length > 0) {
          // Create with explicit foreign key values from parent entities
          code.line(`const item = db.${schema.name}.create({`);
          code.indent();
          for (const fk of fkFields) {
            if (fk.nullable) {
              // Nullable FK: sometimes null, sometimes valid ID
              code.line(`${fk.fieldName}: Math.random() > 0.3 ? pickRandom(ids.${fk.target}) : undefined,`);
            } else {
              // Required FK: always use valid parent ID
              code.line(`${fk.fieldName}: pickRandom(ids.${fk.target}),`);
            }
          }
          code.dedent();
          code.line(`// eslint-disable-next-line @typescript-eslint/no-explicit-any`);
          code.line('} as any);');
        } else {
          code.line(`const item = db.${schema.name}.create({});`);
        }
        code.line(`ids.${schema.name}.push(item.id);`);
      });
      code.line();
    }
  });
  code.line();

  // Reset function
  code.block('export function reset(): void {', () => {
    // Delete in reverse order (dependents first)
    for (const schema of [...schemas].reverse()) {
      code.line(`db.${schema.name}.deleteMany({ where: {} });`);
    }
  });
  code.line();

  // Get all function (for debugging)
  code.block('export function getAll(): Record<string, unknown[]> {', () => {
    code.block('return {', () => {
      for (const schema of schemas) {
        code.line(`${schema.name}: db.${schema.name}.getAll(),`);
      }
    }, '};');
  });

  return code.toString();
}
