/**
 * Integration tests for Fetch client generator
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { generateFetchClient } from '../../../cli/generators/fetch/client';
import { schemas as blogSchemas } from '../fixtures/schemas/blog.schema';
import {
  createTempDir,
  cleanupTempDir,
  analyzeTestSchemas,
} from '../utils/test-helpers';
import { assertCodeContains } from '../utils/compile-checker';
import type { FetchAdapterConfig } from '../../../cli/types';

describe('Fetch Client Generator Integration', () => {
  let tempDir: string;

  beforeAll(async () => {
    tempDir = await createTempDir('fetch-client-test-');
  });

  afterAll(async () => {
    await cleanupTempDir(tempDir);
  });

  it('generates fetch helper function', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FetchAdapterConfig = { baseUrl: '/api' };
    const code = generateFetchClient(analyzed, config);

    assertCodeContains(code, [
      'async function request<T>(',
      'await fetch(',
      "headers: { 'Content-Type': 'application/json'",
    ]);
  });

  it('generates api object with entity methods', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FetchAdapterConfig = { baseUrl: '/api' };
    const code = generateFetchClient(analyzed, config);

    assertCodeContains(code, [
      'export const api = {',
      'user: {',
      'list:',
      'get:',
      'create:',
      'update:',
    ]);
  });

  it('uses configured baseUrl', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FetchAdapterConfig = { baseUrl: 'https://api.example.com' };
    const code = generateFetchClient(analyzed, config);

    expect(code).toContain("const BASE_URL = 'https://api.example.com'");
  });

  it('uses empty baseUrl when not configured', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FetchAdapterConfig = {};
    const code = generateFetchClient(analyzed, config);

    expect(code).toContain("const BASE_URL = ''");
  });

  it('generates query string builder', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FetchAdapterConfig = {};
    const code = generateFetchClient(analyzed, config);

    assertCodeContains(code, [
      'function buildQuery(',
      'URLSearchParams',
    ]);
  });

  it('handles 204 No Content responses', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FetchAdapterConfig = {};
    const code = generateFetchClient(analyzed, config);

    expect(code).toContain('response.status === 204');
  });

  it('includes GENERATED BY header', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FetchAdapterConfig = {};
    const code = generateFetchClient(analyzed, config);

    expect(code).toContain('GENERATED BY SCHEMOCK');
  });

  it('imports types from types file', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FetchAdapterConfig = {};
    const code = generateFetchClient(analyzed, config);

    expect(code).toContain("import type * as Types from './types'");
  });

  it('handles error responses', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FetchAdapterConfig = {};
    const code = generateFetchClient(analyzed, config);

    expect(code).toContain('throw new Error');
    expect(code).toContain('response.ok');
  });

  it('handles empty schema array', () => {
    const analyzed = analyzeTestSchemas([]);
    const config: FetchAdapterConfig = { baseUrl: '/api' };
    const code = generateFetchClient(analyzed, config);

    // Should still generate valid structure
    assertCodeContains(code, [
      'export const api = {',
    ]);
  });
});
