/**
 * Integration tests for Firebase client generator
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { generateFirebaseClient } from '../../../cli/generators/firebase/client';
import { schemas as blogSchemas } from '../fixtures/schemas/blog.schema';
import {
  createTempDir,
  cleanupTempDir,
  analyzeTestSchemas,
} from '../utils/test-helpers';
import { assertCodeContains } from '../utils/compile-checker';
import type { FirebaseAdapterConfig } from '../../../cli/types';

describe('Firebase Client Generator Integration', () => {
  let tempDir: string;

  beforeAll(async () => {
    tempDir = await createTempDir('firebase-client-test-');
  });

  afterAll(async () => {
    await cleanupTempDir(tempDir);
  });

  it('generates Firebase Firestore imports', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FirebaseAdapterConfig = {};
    const code = generateFirebaseClient(analyzed, config);

    assertCodeContains(code, [
      'collection,',
      'doc,',
      'getDoc,',
      'getDocs,',
      'addDoc,',
      'updateDoc,',
      'deleteDoc,',
      'query,',
      'where,',
      'orderBy,',
    ]);
  });

  it('imports from firebase/firestore', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FirebaseAdapterConfig = {};
    const code = generateFirebaseClient(analyzed, config);

    expect(code).toContain("from 'firebase/firestore'");
  });

  it('generates api object with entity methods', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FirebaseAdapterConfig = {};
    const code = generateFirebaseClient(analyzed, config);

    assertCodeContains(code, [
      'export const api = createClient();',
      'user: {',
    ]);
  });

  it('generates CRUD operations', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FirebaseAdapterConfig = {};
    const code = generateFirebaseClient(analyzed, config);

    // Should have Firestore operation patterns
    expect(code).toContain('getDoc(');
    expect(code).toContain('getDocs(');
    expect(code).toContain('addDoc(');
    expect(code).toContain('updateDoc(');
    expect(code).toContain('deleteDoc(');
  });

  it('handles collection name mapping', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FirebaseAdapterConfig = {
      collectionMap: { user: 'appUsers' },
    };
    const code = generateFirebaseClient(analyzed, config);

    expect(code).toContain("'appUsers'");
  });

  it('uses where clauses for filtering', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FirebaseAdapterConfig = {};
    const code = generateFirebaseClient(analyzed, config);

    expect(code).toContain('where(');
  });

  it('includes GENERATED BY header', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FirebaseAdapterConfig = {};
    const code = generateFirebaseClient(analyzed, config);

    expect(code).toContain('GENERATED BY SCHEMOCK');
  });

  it('imports types from types file', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FirebaseAdapterConfig = {};
    const code = generateFirebaseClient(analyzed, config);

    expect(code).toContain("import type * as Types from './types'");
  });

  it('imports firebase instance from lib', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: FirebaseAdapterConfig = {};
    const code = generateFirebaseClient(analyzed, config);

    expect(code).toContain("import { db as firestore } from '../lib/firebase'");
  });

  it('handles empty schema array', () => {
    const analyzed = analyzeTestSchemas([]);
    const config: FirebaseAdapterConfig = {};
    const code = generateFirebaseClient(analyzed, config);

    // Should still generate valid structure
    assertCodeContains(code, [
      'export const api = createClient();',
    ]);
  });
});
