/**
 * Integration tests for React hooks generator
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { generateHooks } from '../../../cli/generators/hooks';
import { schemas as blogSchemas } from '../fixtures/schemas/blog.schema';
import {
  createTempDir,
  cleanupTempDir,
  analyzeTestSchemas,
} from '../utils/test-helpers';
import { assertCodeContains } from '../utils/compile-checker';

describe('Hooks Generator Integration', () => {
  let tempDir: string;

  beforeAll(async () => {
    tempDir = await createTempDir('hooks-test-');
  });

  afterAll(async () => {
    await cleanupTempDir(tempDir);
  });

  it('generates React Query imports', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const code = generateHooks(analyzed);

    // Should import from @tanstack/react-query
    expect(code).toContain('@tanstack/react-query');
  });

  it('generates useEntity hooks for each schema', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const code = generateHooks(analyzed);

    assertCodeContains(code, [
      'useUsers',
      'useUser',
      'usePosts',
      'usePost',
      'useComments',
      'useComment',
    ]);
  });

  it('generates CRUD mutation hooks', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const code = generateHooks(analyzed);

    assertCodeContains(code, [
      'useCreateUser',
      'useUpdateUser',
      'useDeleteUser',
      'useCreatePost',
      'useUpdatePost',
      'useDeletePost',
    ]);
  });

  it('generates convenience hooks for relations', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const code = generateHooks(analyzed);

    // Should have hooks that load related data
    expect(code).toMatch(/useUserWith|usePostWith/);
  });

  it('generates query key helpers', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const code = generateHooks(analyzed);

    // Should have query key patterns for cache invalidation
    expect(code).toMatch(/queryKey|QueryKey/);
  });

  it('includes enabled option for conditional fetching', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const code = generateHooks(analyzed);

    expect(code).toContain('enabled');
  });

  it('includes GENERATED BY header', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const code = generateHooks(analyzed);

    expect(code).toContain('GENERATED BY SCHEMOCK');
  });

  it('handles empty schema array', () => {
    const analyzed = analyzeTestSchemas([]);
    const code = generateHooks(analyzed);

    // Should still be valid code (possibly just header)
    expect(code).toBeDefined();
    expect(typeof code).toBe('string');
  });
});
