/**
 * Integration tests for Mock DB generator (@mswjs/data)
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { generateMockDb } from '../../../cli/generators/mock/db';
import { schemas as blogSchemas } from '../fixtures/schemas/blog.schema';
import {
  createTempDir,
  cleanupTempDir,
  analyzeTestSchemas,
} from '../utils/test-helpers';
import { assertCodeContains, assertCodeDoesNotContain } from '../utils/compile-checker';
import type { MockAdapterConfig } from '../../../cli/types';

describe('Mock DB Generator Integration', () => {
  let tempDir: string;

  beforeAll(async () => {
    tempDir = await createTempDir('mock-db-test-');
  });

  afterAll(async () => {
    await cleanupTempDir(tempDir);
  });

  it('generates @mswjs/data factory imports', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = {};
    const code = generateMockDb(analyzed, config);

    assertCodeContains(code, [
      "import { factory, primaryKey, nullable } from '@mswjs/data'",
      "import { faker } from '@faker-js/faker'",
    ]);
  });

  it('generates factory export', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = {};
    const code = generateMockDb(analyzed, config);

    assertCodeContains(code, [
      'export const db = factory({',
    ]);
  });

  it('generates entity definitions with correct fields', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = {};
    const code = generateMockDb(analyzed, config);

    assertCodeContains(code, [
      'user: {',
      'post: {',
      'comment: {',
    ]);
  });

  it('generates primaryKey for id fields', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = {};
    const code = generateMockDb(analyzed, config);

    expect(code).toContain('primaryKey(');
  });

  it('handles nullable fields with nullable wrapper', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = {};
    const code = generateMockDb(analyzed, config);

    // content in Post is nullable
    expect(code).toContain('nullable(');
  });

  it('generates localStorage persistence layer by default', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = {};
    const code = generateMockDb(analyzed, config);

    assertCodeContains(code, [
      'localStorage',
    ]);
  });

  it('omits persistence when persistence: memory', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = { persistence: 'memory' };
    const code = generateMockDb(analyzed, config);

    // Should not have persistence functions
    assertCodeDoesNotContain(code, [
      'loadFromStorage',
      'saveToStorage',
    ]);
  });

  it('uses custom storage key when provided', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = { storageKey: 'my-app' };
    const code = generateMockDb(analyzed, config);

    expect(code).toContain('my-app');
  });

  it('uses custom faker seed when provided', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = { fakerSeed: 12345 };
    const code = generateMockDb(analyzed, config);

    expect(code).toContain('faker.seed(12345)');
  });

  it('exports Database type', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = {};
    const code = generateMockDb(analyzed, config);

    expect(code).toContain('export type Database = typeof db');
  });

  it('includes GENERATED BY header', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: MockAdapterConfig = {};
    const code = generateMockDb(analyzed, config);

    expect(code).toContain('GENERATED BY SCHEMOCK');
  });

  it('handles empty schema array', () => {
    const analyzed = analyzeTestSchemas([]);
    const config: MockAdapterConfig = {};
    const code = generateMockDb(analyzed, config);

    // Should still generate valid factory structure
    assertCodeContains(code, [
      'export const db = factory({',
    ]);
  });
});
