/**
 * Integration tests for Node handlers generator
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { generateHandlerFile } from '../../../cli/generators/node-handlers/handler-template';
import { generateRouterFile } from '../../../cli/generators/node-handlers/router-template';
import { schemas as blogSchemas } from '../fixtures/schemas/blog.schema';
import {
  createTempDir,
  cleanupTempDir,
  analyzeTestSchemas,
  createTestConfig,
} from '../utils/test-helpers';
import { assertCodeContains } from '../utils/compile-checker';
import type { GenerationTarget } from '../../../cli/types';

describe('Node Handlers Generator Integration', () => {
  let tempDir: string;

  beforeAll(async () => {
    tempDir = await createTempDir('node-handlers-test-');
  });

  afterAll(async () => {
    await cleanupTempDir(tempDir);
  });

  describe('generateHandlerFile', () => {
    it('generates Express-compatible handler signatures', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'supabase',
      };
      const config = createTestConfig();

      const code = generateHandlerFile(analyzed[0], target, config);

      assertCodeContains(code, [
        "import type { Request, Response, NextFunction } from 'express'",
        'export async function list(',
        'export async function getOne(',
        'export async function create(',
        'export async function update(',
      ]);
    });

    it('imports Supabase backend when backend is supabase', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'supabase',
      };
      const config = createTestConfig();

      const code = generateHandlerFile(analyzed[0], target, config);

      expect(code).toContain("import { supabase } from '../db'");
    });

    it('imports Firebase backend when backend is firebase', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'firebase',
      };
      const config = createTestConfig();

      const code = generateHandlerFile(analyzed[0], target, config);

      expect(code).toContain("import { db } from '../db'");
    });

    it('imports types from types file', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'supabase',
      };
      const config = createTestConfig();

      const code = generateHandlerFile(analyzed[0], target, config);

      expect(code).toContain("from '../types'");
    });

    it('imports validation when validation middleware is enabled', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'supabase',
        middleware: { validation: true },
      };
      const config = createTestConfig();

      const code = generateHandlerFile(analyzed[0], target, config);

      expect(code).toContain('validate');
    });

    it('includes GENERATED BY header', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'supabase',
      };
      const config = createTestConfig();

      const code = generateHandlerFile(analyzed[0], target, config);

      expect(code).toContain('GENERATED BY SCHEMOCK');
    });
  });

  describe('generateRouterFile', () => {
    it('generates Express router setup', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'supabase',
      };
      const config = createTestConfig();

      const code = generateRouterFile(analyzed, target, config);

      assertCodeContains(code, [
        'Router',
        'express',
      ]);
    });

    it('imports handlers for each entity', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'supabase',
      };
      const config = createTestConfig();

      const code = generateRouterFile(analyzed, target, config);

      // Should import from handlers directory
      expect(code).toContain("from './handlers/");
    });

    it('sets up routes for CRUD operations', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'supabase',
      };
      const config = createTestConfig();

      const code = generateRouterFile(analyzed, target, config);

      // Should have route definitions
      expect(code).toContain('.get(');
      expect(code).toContain('.post(');
    });

    it('includes GENERATED BY header', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'supabase',
      };
      const config = createTestConfig();

      const code = generateRouterFile(analyzed, target, config);

      expect(code).toContain('GENERATED BY SCHEMOCK');
    });

    it('handles empty schema array', () => {
      const analyzed = analyzeTestSchemas([]);
      const target: GenerationTarget = {
        name: 'api',
        type: 'node-handlers',
        output: tempDir,
        backend: 'supabase',
      };
      const config = createTestConfig();

      const code = generateRouterFile(analyzed, target, config);

      // Should still generate valid router structure
      expect(code).toContain('Router');
    });
  });
});
