/**
 * Integration tests for Supabase client generator
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { generateSupabaseClient } from '../../../cli/generators/supabase/client';
import { schemas as blogSchemas } from '../fixtures/schemas/blog.schema';
import {
  createTempDir,
  cleanupTempDir,
  analyzeTestSchemas,
} from '../utils/test-helpers';
import { assertCodeContains } from '../utils/compile-checker';
import type { SupabaseAdapterConfig } from '../../../cli/types';

describe('Supabase Client Generator Integration', () => {
  let tempDir: string;

  beforeAll(async () => {
    tempDir = await createTempDir('supabase-client-test-');
  });

  afterAll(async () => {
    await cleanupTempDir(tempDir);
  });

  it('generates Supabase client setup', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    assertCodeContains(code, [
      "import { createClient as createSupabaseClient } from '@supabase/supabase-js'",
      'export const supabase = createSupabaseClient(',
    ]);
  });

  it('uses default NEXT_PUBLIC_SUPABASE env prefix', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    assertCodeContains(code, [
      'process.env.NEXT_PUBLIC_SUPABASE_URL',
      'process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY',
    ]);
  });

  it('uses custom env prefix when provided', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = { envPrefix: 'CUSTOM_SUPABASE' };
    const code = generateSupabaseClient(analyzed, config);

    assertCodeContains(code, [
      'process.env.CUSTOM_SUPABASE_URL',
      'process.env.CUSTOM_SUPABASE_ANON_KEY',
    ]);
  });

  it('generates buildSelect helper for relations', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    assertCodeContains(code, [
      'function buildSelect(',
      "return '*'",
    ]);
  });

  it('generates api object with entity methods', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    assertCodeContains(code, [
      'export const api = createClient();', // Default api export
      'user: {', // Entity methods in the factory
    ]);
  });

  it('generates CRUD methods with proper Supabase syntax', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    // Should have Supabase query builder patterns
    expect(code).toContain('.select(');
    expect(code).toContain('.insert(');
    expect(code).toContain('.update(');
    expect(code).toContain('.delete(');
    expect(code).toContain(".eq('id'");
    expect(code).toContain('.single()');
  });

  it('handles table name mapping', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {
      tableMap: { user: 'app_users' },
    };
    const code = generateSupabaseClient(analyzed, config);

    // The tableMap should affect how tables are referenced
    // In the new interceptor pattern, client.from is used inside the factory
    expect(code).toContain(".from(");
  });

  it('includes GENERATED BY header', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    expect(code).toContain('GENERATED BY SCHEMOCK');
  });

  it('imports types from types file', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    expect(code).toContain("import type * as Types from './types'");
  });

  it('handles empty schema array', () => {
    const analyzed = analyzeTestSchemas([]);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    // Should still generate valid structure with the createClient factory
    assertCodeContains(code, [
      'export function createClient(',
      'export const api = createClient();',
    ]);
  });

  // ============================================================================
  // Interceptor Pattern Tests
  // ============================================================================

  describe('Interceptor Pattern', () => {
    it('generates RequestContext interface', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      assertCodeContains(code, [
        'export interface RequestContext {',
        'headers: Record<string, string>',
        'operation: string',
      ]);
    });

    it('generates ClientConfig interface with onRequest and onError', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      assertCodeContains(code, [
        'export interface ClientConfig {',
        'onRequest?:',
        'onError?:',
      ]);
    });

    it('generates createClient factory function', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      assertCodeContains(code, [
        'export function createClient(config?: ClientConfig): ApiClient {',
      ]);
    });

    it('generates ApiClient type interface', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      assertCodeContains(code, [
        'export interface ApiClient {',
      ]);
    });

    it('exports default api client', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      assertCodeContains(code, [
        'export const api = createClient();',
      ]);
    });
  });

  // ============================================================================
  // Error Handling Tests
  // ============================================================================

  describe('Error Handling', () => {
    it('generates ApiError class', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      assertCodeContains(code, [
        'export class ApiError extends Error {',
        'readonly status: number',
        'readonly code: string',
        'readonly operation: string',
      ]);
    });

    it('generates wrapSupabaseError function', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      assertCodeContains(code, [
        'function wrapSupabaseError(error: unknown, operation: string): ApiError {',
      ]);
    });

    it('maps Supabase error codes to HTTP status codes', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      // Check error code mapping
      assertCodeContains(code, [
        "case 'PGRST116': status = 404", // Not found
        "case '23505': status = 409",    // Unique violation
        "case '42501': status = 403",    // RLS violation
        "case 'PGRST302': status = 401", // JWT expired
      ]);
    });
  });

  // ============================================================================
  // Auth Token Handling Tests
  // ============================================================================

  describe('Auth Token Handling', () => {
    it('generates extractAccessToken helper', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      assertCodeContains(code, [
        'function extractAccessToken(headers: Record<string, string>)',
        "startsWith('Bearer ')",
      ]);
    });

    it('generates getSupabaseClient function for dynamic auth', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      assertCodeContains(code, [
        'function getSupabaseClient(accessToken?: string)',
        'Authorization: `Bearer ${accessToken}`',
      ]);
    });
  });

  // ============================================================================
  // Operation Execution Tests
  // ============================================================================

  describe('Operation Execution', () => {
    it('wraps list operations with executeListRequest', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      assertCodeContains(code, [
        'executeListRequest<',
      ]);
    });

    it('wraps get/create/update operations with executeRequest', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      // Should have executeRequest calls for non-list operations
      expect(code).toContain("executeRequest<");
    });

    it('generates proper operation names for interceptors', () => {
      const analyzed = analyzeTestSchemas(blogSchemas);
      const config: SupabaseAdapterConfig = {};
      const code = generateSupabaseClient(analyzed, config);

      // Check operation names are passed
      assertCodeContains(code, [
        "'user.list'",
        "'user.get'",
        "'user.create'",
        "'user.update'",
        "'user.delete'",
      ]);
    });
  });
});
