/**
 * Integration tests for Supabase client generator
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { generateSupabaseClient } from '../../../cli/generators/supabase/client';
import { schemas as blogSchemas } from '../fixtures/schemas/blog.schema';
import {
  createTempDir,
  cleanupTempDir,
  analyzeTestSchemas,
} from '../utils/test-helpers';
import { assertCodeContains } from '../utils/compile-checker';
import type { SupabaseAdapterConfig } from '../../../cli/types';

describe('Supabase Client Generator Integration', () => {
  let tempDir: string;

  beforeAll(async () => {
    tempDir = await createTempDir('supabase-client-test-');
  });

  afterAll(async () => {
    await cleanupTempDir(tempDir);
  });

  it('generates Supabase client setup', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    assertCodeContains(code, [
      "import { createClient } from '@supabase/supabase-js'",
      'export const supabase = createClient(',
    ]);
  });

  it('uses default NEXT_PUBLIC_SUPABASE env prefix', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    assertCodeContains(code, [
      'process.env.NEXT_PUBLIC_SUPABASE_URL',
      'process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY',
    ]);
  });

  it('uses custom env prefix when provided', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = { envPrefix: 'CUSTOM_SUPABASE' };
    const code = generateSupabaseClient(analyzed, config);

    assertCodeContains(code, [
      'process.env.CUSTOM_SUPABASE_URL',
      'process.env.CUSTOM_SUPABASE_ANON_KEY',
    ]);
  });

  it('generates buildSelect helper for relations', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    assertCodeContains(code, [
      'function buildSelect(',
      "return '*'",
    ]);
  });

  it('generates api object with entity methods', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    assertCodeContains(code, [
      'export const api = {',
      'user: {',
    ]);
  });

  it('generates CRUD methods with proper Supabase syntax', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    // Should have Supabase query builder patterns
    expect(code).toContain('.select(');
    expect(code).toContain('.insert(');
    expect(code).toContain('.update(');
    expect(code).toContain('.delete(');
    expect(code).toContain(".eq('id'");
    expect(code).toContain('.single()');
  });

  it('handles table name mapping', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {
      tableMap: { user: 'app_users' },
    };
    const code = generateSupabaseClient(analyzed, config);

    // The tableMap should affect how tables are referenced
    // Check that user entity uses custom table name or supabase.from is called
    expect(code).toContain("supabase.from(");
  });

  it('includes GENERATED BY header', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    expect(code).toContain('GENERATED BY SCHEMOCK');
  });

  it('imports types from types file', () => {
    const analyzed = analyzeTestSchemas(blogSchemas);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    expect(code).toContain("import type * as Types from './types'");
  });

  it('handles empty schema array', () => {
    const analyzed = analyzeTestSchemas([]);
    const config: SupabaseAdapterConfig = {};
    const code = generateSupabaseClient(analyzed, config);

    // Should still generate valid structure
    assertCodeContains(code, [
      'export const api = {',
    ]);
  });
});
