/**
 * Supabase Edge Function Templates
 *
 * Generates Deno-based Edge Function handlers from Schemock schemas.
 * Supports both individual functions per entity and "fat functions" approach.
 *
 * @module cli/generators/supabase-edge/function-template
 * @category CLI
 */

import type { AnalyzedSchema, GenerationTarget, SchemockConfig } from '../../types';

/**
 * Generate an Edge Function file for a single entity
 */
export function generateEdgeFunctionFile(
  schema: AnalyzedSchema,
  target: GenerationTarget,
  config: SchemockConfig
): string {
  const hasNewMiddlewareConfig = config.middleware !== undefined;
  const lines: string[] = [
    '// GENERATED BY SCHEMOCK - DO NOT EDIT',
    "// Supabase Edge Function for: " + schema.pluralName,
    '',
    "import { corsHeaders } from '../_shared/cors.ts';",
    "import { supabase } from '../_shared/supabase.ts';",
    `import type { ${schema.pascalName}, ${schema.pascalName}Create, ${schema.pascalName}Update } from '../_shared/types.ts';`,
  ];

  // Import middleware chain if using new config
  if (hasNewMiddlewareConfig) {
    lines.push("import { runMiddlewareChain, type MiddlewareChainContext } from '../_shared/middleware/chain.ts';");
  }

  lines.push('');
  lines.push('Deno.serve(async (req) => {');
  lines.push('  // Handle CORS preflight');
  lines.push("  if (req.method === 'OPTIONS') {");
  lines.push("    return new Response('ok', { headers: corsHeaders() });");
  lines.push('  }');
  lines.push('');

  // Add middleware chain call if using new config
  if (hasNewMiddlewareConfig) {
    lines.push('  // Run middleware chain');
    lines.push(`  const mwResult = await runMiddlewareChain(req, '${schema.tableName}');`);
    lines.push('  if (mwResult.error) {');
    lines.push('    return mwResult.response!;');
    lines.push('  }');
    lines.push('  const ctx = mwResult.context;');
    lines.push('');
  }

  lines.push('  const { method, url } = req;');
  lines.push('  const { pathname, searchParams } = new URL(url);');
  lines.push('');
  lines.push('  // Extract ID from path if present');
  lines.push("  const idMatch = pathname.match(/\\/([a-zA-Z0-9-]+)$/);");
  lines.push('  const id = idMatch ? idMatch[1] : null;');
  lines.push('');
  lines.push('  try {');

  // GET list
  lines.push("    if (method === 'GET' && !id) {");
  lines.push("      const limit = parseInt(searchParams.get('limit') || '20', 10);");
  lines.push("      const offset = parseInt(searchParams.get('offset') || '0', 10);");
  lines.push('');
  lines.push(`      const { data, error, count } = await supabase`);
  lines.push(`        .from('${schema.tableName}')`);
  lines.push("        .select('*', { count: 'exact' })");
  lines.push('        .range(offset, offset + limit - 1);');
  lines.push('');
  lines.push('      if (error) {');
  lines.push('        return jsonResponse({ error: error.message }, 500);');
  lines.push('      }');
  lines.push('');
  lines.push('      return jsonResponse({ data, meta: { total: count ?? 0, limit, offset } });');
  lines.push('    }');
  lines.push('');

  // GET single
  lines.push("    if (method === 'GET' && id) {");
  lines.push(`      const { data, error } = await supabase`);
  lines.push(`        .from('${schema.tableName}')`);
  lines.push("        .select('*')");
  lines.push("        .eq('id', id)");
  lines.push('        .single();');
  lines.push('');
  lines.push('      if (error) {');
  lines.push("        if (error.code === 'PGRST116') {");
  lines.push("          return jsonResponse({ error: 'Not found' }, 404);");
  lines.push('        }');
  lines.push('        return jsonResponse({ error: error.message }, 500);');
  lines.push('      }');
  lines.push('');
  lines.push('      return jsonResponse(data);');
  lines.push('    }');
  lines.push('');

  // POST create
  lines.push("    if (method === 'POST') {");
  lines.push(`      const body = await req.json() as ${schema.pascalName}Create;`);
  lines.push('');
  lines.push(`      const { data, error } = await supabase`);
  lines.push(`        .from('${schema.tableName}')`);
  lines.push('        .insert(body)');
  lines.push('        .select()');
  lines.push('        .single();');
  lines.push('');
  lines.push('      if (error) {');
  lines.push('        return jsonResponse({ error: error.message }, 500);');
  lines.push('      }');
  lines.push('');
  lines.push('      return jsonResponse(data, 201);');
  lines.push('    }');
  lines.push('');

  // PUT update
  lines.push("    if (method === 'PUT' && id) {");
  lines.push(`      const body = await req.json() as ${schema.pascalName}Update;`);
  lines.push('');
  lines.push(`      const { data, error } = await supabase`);
  lines.push(`        .from('${schema.tableName}')`);
  lines.push('        .update(body)');
  lines.push("        .eq('id', id)");
  lines.push('        .select()');
  lines.push('        .single();');
  lines.push('');
  lines.push('      if (error) {');
  lines.push("        if (error.code === 'PGRST116') {");
  lines.push("          return jsonResponse({ error: 'Not found' }, 404);");
  lines.push('        }');
  lines.push('        return jsonResponse({ error: error.message }, 500);');
  lines.push('      }');
  lines.push('');
  lines.push('      return jsonResponse(data);');
  lines.push('    }');
  lines.push('');

  // DELETE
  lines.push("    if (method === 'DELETE' && id) {");
  lines.push(`      const { error } = await supabase`);
  lines.push(`        .from('${schema.tableName}')`);
  lines.push('        .delete()');
  lines.push("        .eq('id', id);");
  lines.push('');
  lines.push('      if (error) {');
  lines.push('        return jsonResponse({ error: error.message }, 500);');
  lines.push('      }');
  lines.push('');
  lines.push('      return new Response(null, { status: 204, headers: corsHeaders() });');
  lines.push('    }');
  lines.push('');

  // 404 fallback
  lines.push("    return jsonResponse({ error: 'Not found' }, 404);");
  lines.push('  } catch (error) {');
  lines.push("    console.error('Edge function error:', error);");
  lines.push("    return jsonResponse({ error: 'Internal server error' }, 500);");
  lines.push('  }');
  lines.push('});');
  lines.push('');

  // Helper function
  lines.push('/**');
  lines.push(' * Create a JSON response with CORS headers');
  lines.push(' */');
  lines.push('function jsonResponse(data: unknown, status: number = 200): Response {');
  lines.push('  return new Response(JSON.stringify(data), {');
  lines.push('    status,');
  lines.push('    headers: {');
  lines.push("      'Content-Type': 'application/json',");
  lines.push('      ...corsHeaders(),');
  lines.push('    },');
  lines.push('  });');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate a "fat function" file that handles all entities
 * This approach reduces cold starts by combining related endpoints
 */
export function generateFatFunctionFile(
  schemas: AnalyzedSchema[],
  target: GenerationTarget,
  config: SchemockConfig,
  functionName: string
): string {
  const hasNewMiddlewareConfig = config.middleware !== undefined;
  const nonJunctionSchemas = schemas.filter(s => !s.isJunctionTable);

  const lines: string[] = [
    '// GENERATED BY SCHEMOCK - DO NOT EDIT',
    `// Supabase Edge Function: ${functionName}`,
    '// Fat function approach - handles all entities in one function',
    '',
    "import { corsHeaders } from '../_shared/cors.ts';",
    "import { supabase } from '../_shared/supabase.ts';",
    "import type {",
  ];

  // Import all types
  for (const schema of nonJunctionSchemas) {
    lines.push(`  ${schema.pascalName},`);
    lines.push(`  ${schema.pascalName}Create,`);
    lines.push(`  ${schema.pascalName}Update,`);
  }
  lines.push("} from '../_shared/types.ts';");

  // Import middleware chain if using new config
  if (hasNewMiddlewareConfig) {
    lines.push("import { runMiddlewareChain, type MiddlewareChainContext } from '../_shared/middleware/chain.ts';");
  }

  lines.push('');
  lines.push('/**');
  lines.push(' * Entity configuration for routing');
  lines.push(' */');
  lines.push('const entities = {');
  for (const schema of nonJunctionSchemas) {
    lines.push(`  '${schema.pluralName}': { table: '${schema.tableName}' },`);
  }
  lines.push('} as const;');
  lines.push('');
  lines.push('type EntityName = keyof typeof entities;');
  lines.push('');

  lines.push('Deno.serve(async (req) => {');
  lines.push('  // Handle CORS preflight');
  lines.push("  if (req.method === 'OPTIONS') {");
  lines.push("    return new Response('ok', { headers: corsHeaders() });");
  lines.push('  }');
  lines.push('');
  lines.push('  const { method, url } = req;');
  lines.push('  const { pathname, searchParams } = new URL(url);');
  lines.push('');
  lines.push(`  // Parse route: /${functionName}/[entity]/[id?]`);
  lines.push(`  const routeMatch = pathname.match(/^\\/${functionName}\\/([a-z]+)(?:\\/([a-zA-Z0-9-]+))?$/);`);
  lines.push('  if (!routeMatch) {');
  lines.push("    return jsonResponse({ error: 'Invalid route' }, 404);");
  lines.push('  }');
  lines.push('');
  lines.push('  const entityName = routeMatch[1] as EntityName;');
  lines.push('  const id = routeMatch[2] || null;');
  lines.push('');
  lines.push('  // Validate entity');
  lines.push('  if (!(entityName in entities)) {');
  lines.push("    return jsonResponse({ error: `Unknown entity: ${entityName}` }, 404);");
  lines.push('  }');
  lines.push('');
  lines.push('  const { table } = entities[entityName];');
  lines.push('');

  // Add middleware chain call if using new config
  if (hasNewMiddlewareConfig) {
    lines.push('  // Run middleware chain');
    lines.push('  const operation = method === "GET" ? "select"');
    lines.push('    : method === "POST" ? "insert"');
    lines.push('    : method === "PUT" ? "update"');
    lines.push('    : method === "DELETE" ? "delete"');
    lines.push('    : "select";');
    lines.push('  const mwResult = await runMiddlewareChain(req, table, operation);');
    lines.push('  if (mwResult.error) {');
    lines.push('    return mwResult.response!;');
    lines.push('  }');
    lines.push('  const ctx = mwResult.context;');
    lines.push('');
  }

  lines.push('  try {');

  // GET list
  lines.push("    if (method === 'GET' && !id) {");
  lines.push("      const limit = parseInt(searchParams.get('limit') || '20', 10);");
  lines.push("      const offset = parseInt(searchParams.get('offset') || '0', 10);");
  lines.push('');
  lines.push('      const { data, error, count } = await supabase');
  lines.push('        .from(table)');
  lines.push("        .select('*', { count: 'exact' })");
  lines.push('        .range(offset, offset + limit - 1);');
  lines.push('');
  lines.push('      if (error) {');
  lines.push('        return jsonResponse({ error: error.message }, 500);');
  lines.push('      }');
  lines.push('');
  lines.push('      return jsonResponse({ data, meta: { total: count ?? 0, limit, offset } });');
  lines.push('    }');
  lines.push('');

  // GET single
  lines.push("    if (method === 'GET' && id) {");
  lines.push('      const { data, error } = await supabase');
  lines.push('        .from(table)');
  lines.push("        .select('*')");
  lines.push("        .eq('id', id)");
  lines.push('        .single();');
  lines.push('');
  lines.push('      if (error) {');
  lines.push("        if (error.code === 'PGRST116') {");
  lines.push("          return jsonResponse({ error: 'Not found' }, 404);");
  lines.push('        }');
  lines.push('        return jsonResponse({ error: error.message }, 500);');
  lines.push('      }');
  lines.push('');
  lines.push('      return jsonResponse(data);');
  lines.push('    }');
  lines.push('');

  // POST create
  lines.push("    if (method === 'POST') {");
  lines.push('      const body = await req.json();');
  lines.push('');
  lines.push('      const { data, error } = await supabase');
  lines.push('        .from(table)');
  lines.push('        .insert(body)');
  lines.push('        .select()');
  lines.push('        .single();');
  lines.push('');
  lines.push('      if (error) {');
  lines.push('        return jsonResponse({ error: error.message }, 500);');
  lines.push('      }');
  lines.push('');
  lines.push('      return jsonResponse(data, 201);');
  lines.push('    }');
  lines.push('');

  // PUT update
  lines.push("    if (method === 'PUT' && id) {");
  lines.push('      const body = await req.json();');
  lines.push('');
  lines.push('      const { data, error } = await supabase');
  lines.push('        .from(table)');
  lines.push('        .update(body)');
  lines.push("        .eq('id', id)");
  lines.push('        .select()');
  lines.push('        .single();');
  lines.push('');
  lines.push('      if (error) {');
  lines.push("        if (error.code === 'PGRST116') {");
  lines.push("          return jsonResponse({ error: 'Not found' }, 404);");
  lines.push('        }');
  lines.push('        return jsonResponse({ error: error.message }, 500);');
  lines.push('      }');
  lines.push('');
  lines.push('      return jsonResponse(data);');
  lines.push('    }');
  lines.push('');

  // DELETE
  lines.push("    if (method === 'DELETE' && id) {");
  lines.push('      const { error } = await supabase');
  lines.push('        .from(table)');
  lines.push('        .delete()');
  lines.push("        .eq('id', id);");
  lines.push('');
  lines.push('      if (error) {');
  lines.push('        return jsonResponse({ error: error.message }, 500);');
  lines.push('      }');
  lines.push('');
  lines.push('      return new Response(null, { status: 204, headers: corsHeaders() });');
  lines.push('    }');
  lines.push('');

  // Method not allowed
  lines.push("    return jsonResponse({ error: 'Method not allowed' }, 405);");
  lines.push('  } catch (error) {');
  lines.push("    console.error('Edge function error:', error);");
  lines.push("    return jsonResponse({ error: 'Internal server error' }, 500);");
  lines.push('  }');
  lines.push('});');
  lines.push('');

  // Helper function
  lines.push('/**');
  lines.push(' * Create a JSON response with CORS headers');
  lines.push(' */');
  lines.push('function jsonResponse(data: unknown, status: number = 200): Response {');
  lines.push('  return new Response(JSON.stringify(data), {');
  lines.push('    status,');
  lines.push('    headers: {');
  lines.push("      'Content-Type': 'application/json',");
  lines.push('      ...corsHeaders(),');
  lines.push('    },');
  lines.push('  });');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
