/**
 * Supabase Edge Seed Function Template
 *
 * Generates the `_seed/index.ts` Edge Function for production seeding via HTTP endpoint.
 *
 * @module cli/generators/supabase-edge/seed-function-template
 * @category CLI
 */

import type { AnalyzedSchema, GenerationTarget, SchemockConfig } from '../../types';
import { CodeBuilder } from '../../utils/code-builder';
import {
  emitSeedRefHelpers,
  emitEntityOrderAndTableMap,
  emitSeedTypes,
  emitSupabaseKillSwitchHelpers,
  emitSupabaseInsertLogic,
} from '../shared/seed-handler-helpers';

/**
 * Generate the seed Edge Function file
 *
 * @param schemas - Analyzed schemas (topologically sorted)
 * @param target - Target configuration
 * @param config - Schemock config
 * @returns Generated TypeScript code
 */
export function generateSeedEdgeFunction(
  schemas: AnalyzedSchema[],
  target: GenerationTarget,
  config: SchemockConfig
): string {
  const code = new CodeBuilder();

  code.comment('GENERATED BY SCHEMOCK - DO NOT EDIT');
  code.comment('Supabase Edge Function for: production seed');
  code.line();

  // Imports - Deno style
  code.line("import { corsHeaders } from '../_shared/cors.ts';");
  code.line("import { supabase } from '../_shared/supabase.ts';");
  code.line();

  // Emit types
  emitSeedTypes(code);

  // Emit entity order and table name mapping
  emitEntityOrderAndTableMap(code, schemas);

  // Emit seed reference helpers
  emitSeedRefHelpers(code);

  // Emit kill switch helpers for Supabase
  emitSupabaseKillSwitchHelpers(code);

  // JSON response helper
  code.comment('JSON response helper');
  code.block(
    'function jsonResponse(data: unknown, status = 200): Response {',
    () => {
      code.line('return new Response(JSON.stringify(data), {');
      code.line('  status,');
      code.line('  headers: {');
      code.line("    ...corsHeaders(),");
      code.line("    'Content-Type': 'application/json',");
      code.line('  },');
      code.line('});');
    }
  );
  code.line();

  // Main Deno.serve handler
  generateDenoServeHandler(code, config);

  return code.toString();
}

/**
 * Generate the Deno.serve handler
 */
function generateDenoServeHandler(code: CodeBuilder, config: SchemockConfig): void {
  code.block('Deno.serve(async (req) => {', () => {
    // Handle CORS preflight
    code.comment('Handle CORS preflight');
    code.block("if (req.method === 'OPTIONS') {", () => {
      code.line("return new Response('ok', { headers: corsHeaders() });");
    });
    code.line();

    // Environment guard
    code.comment('Environment guard: only allow with explicit flag in production');
    code.block("if (Deno.env.get('SCHEMOCK_ALLOW_SEED') !== 'true') {", () => {
      code.line("return jsonResponse({ error: 'Seed endpoint disabled' }, 403);");
    });
    code.line();

    // Only allow POST
    code.block("if (req.method !== 'POST') {", () => {
      code.line("return jsonResponse({ error: 'Method not allowed' }, 405);");
    });
    code.line();

    code.block('try {', () => {
      code.line('const body = await req.json().catch(() => ({}));');
      code.line('const { secret } = body;');
      code.line();

      // Validate secret is present
      code.block("if (!secret || typeof secret !== 'string') {", () => {
        code.line("return jsonResponse({ success: false, error: 'MISSING_SECRET' } as SeedResult, 400);");
      });
      code.line();

      // Dynamic import of seed data - Edge Functions use relative imports
      code.comment('Note: In Supabase Edge Functions, seed data should be imported from _shared');
      code.comment('For production, compile seed-data.ts and deploy with the function');
      const seedDataPath = config.productionSeed?.dataPath || './src/seed-data';
      const cleanPath = seedDataPath.replace(/^\.\//, '').replace(/\.ts$/, '');
      code.line("// @ts-ignore - Dynamic import");
      code.line(`const seedModule = await import('../_shared/seed-data.ts').catch(() => {`);
      code.line("  throw new Error('seed-data.ts not found in _shared. Copy your seed data to supabase/functions/_shared/seed-data.ts');");
      code.line('});');
      code.line('const seedConfig: ProductionSeedData = seedModule.seedConfig ?? seedModule.default;');
      code.line();

      // Validate secret
      code.comment('1. Validate secret');
      code.block('if (secret !== seedConfig.secret) {', () => {
        code.line("return jsonResponse({ success: false, error: 'INVALID_SECRET' } as SeedResult, 401);");
      });
      code.line();

      // Check kill switch
      code.comment('2. Check kill switch');
      code.block('if (await isSeeded()) {', () => {
        code.line('const seededAt = await getSeededAt();');
        code.line('return jsonResponse({');
        code.line('  success: false,');
        code.line("  error: 'ALREADY_SEEDED',");
        code.line('  seededAt: seededAt ?? undefined,');
        code.line('} as SeedResult, 409);');
      });
      code.line();

      // Insert data in order
      code.comment('3. Insert data for each entity (ordered by dependencies)');
      code.line('const createdRecords = new Map<string, Record<string, unknown>[]>();');
      code.line();

      code.comment('Determine insertion order: entityOrder first, then any remaining keys');
      code.line('const orderedEntities = [');
      code.line('  ...entityOrder.filter((e) => e in seedConfig.data),');
      code.line('  ...Object.keys(seedConfig.data).filter((e) => !entityOrder.includes(e)),');
      code.line('];');
      code.line();

      // Emit Supabase INSERT logic
      emitSupabaseInsertLogic(code);
      code.line();

      // Set kill switch
      code.comment('4. Set kill switch');
      code.line('await setSeeded();');
      code.line('const seededAt = new Date();');
      code.line();

      code.line("console.log('\\u2713 Production data seeded via Edge Function');");
      code.line('return jsonResponse({ success: true, seededAt } as SeedResult);');
    }, '} catch (error) {');
    code.indent();
    code.line("console.error('Seed error:', error);");
    code.line('return jsonResponse(');
    code.line("  { error: error instanceof Error ? error.message : 'Unknown error' },");
    code.line('  500');
    code.line(');');
    code.dedent();
    code.line('}');
  }, '});');
}
