/**
 * Neon Router Template
 *
 * Generates the main Express router that combines all entity handlers.
 *
 * @module cli/generators/neon/router-template
 * @category CLI
 */

import type { AnalyzedSchema, AnalyzedEndpoint, GenerationTarget, SchemockConfig } from '../../types';

/**
 * Generate the main router file
 */
export function generateRouterFile(
  schemas: AnalyzedSchema[],
  target: GenerationTarget,
  config: SchemockConfig,
  endpoints: AnalyzedEndpoint[] = [],
  hasProductionSeed: boolean = false
): string {
  const apiPrefix = config.apiPrefix || '/api';
  const hasNewMiddlewareConfig = config.middleware !== undefined;

  const lines: string[] = [
    '// GENERATED BY SCHEMOCK - DO NOT EDIT',
    '',
    "import { Router } from 'express';",
  ];

  // Import handlers for each entity
  for (const schema of schemas) {
    if (schema.isJunctionTable) continue;
    lines.push(`import * as ${schema.pluralName}Handlers from './handlers/${schema.pluralName}';`);
  }

  // Import endpoint handlers
  for (const endpoint of endpoints) {
    lines.push(`import * as ${endpoint.name}Endpoint from './handlers/${endpoint.name}';`);
  }

  // Import seed handler if production seed is configured
  if (hasProductionSeed) {
    lines.push("import * as seedHandler from './handlers/_seed';");
  }

  // Import middleware if configured
  if (hasNewMiddlewareConfig) {
    lines.push("import { applyMiddleware } from './middleware/chain';");
  } else if (target.middleware?.auth) {
    lines.push("import { authMiddleware } from './middleware/auth';");
  }

  lines.push('');

  // Export router factory function
  lines.push('/**');
  lines.push(' * Create and configure the API router');
  lines.push(' * @param options - Router configuration options');
  lines.push(' */');
  lines.push('export function createRouter(options: {');
  lines.push('  /** Skip auth for these paths */');
  lines.push('  skipAuth?: string[];');
  lines.push('  /** Custom middleware to apply */');
  lines.push('  middleware?: Array<(req: any, res: any, next: any) => void>;');
  lines.push('} = {}): Router {');
  lines.push('  const router = Router();');
  lines.push('');

  // Apply global middleware
  if (hasNewMiddlewareConfig) {
    lines.push('  // Apply middleware chain from config');
    lines.push('  applyMiddleware(router, options.skipAuth);');
  } else if (target.middleware?.auth) {
    lines.push('  // Apply auth middleware');
    lines.push('  router.use(authMiddleware);');
  }

  lines.push('');
  lines.push('  // Apply custom middleware');
  lines.push('  if (options.middleware) {');
  lines.push('    options.middleware.forEach(mw => router.use(mw));');
  lines.push('  }');
  lines.push('');

  // Register routes for each entity
  for (const schema of schemas) {
    if (schema.isJunctionTable) continue;

    lines.push(`  // ${schema.pascalName} routes`);
    lines.push(`  router.get('${apiPrefix}/${schema.pluralName}', ${schema.pluralName}Handlers.list);`);
    lines.push(`  router.get('${apiPrefix}/${schema.pluralName}/:id', ${schema.pluralName}Handlers.getOne);`);
    lines.push(`  router.post('${apiPrefix}/${schema.pluralName}', ${schema.pluralName}Handlers.create);`);
    lines.push(`  router.put('${apiPrefix}/${schema.pluralName}/:id', ${schema.pluralName}Handlers.update);`);
    lines.push(`  router.delete('${apiPrefix}/${schema.pluralName}/:id', ${schema.pluralName}Handlers.remove);`);
    lines.push('');
  }

  // Register custom endpoint routes
  if (endpoints.length > 0) {
    lines.push('  // Custom endpoint routes');
    for (const endpoint of endpoints) {
      const method = endpoint.method.toLowerCase();
      // Use the full path (already includes prefix)
      lines.push(`  router.${method}('${endpoint.path}', ${endpoint.name}Endpoint.handler);`);
    }
    lines.push('');
  }

  // Register seed endpoint (with environment guard)
  if (hasProductionSeed) {
    lines.push('  // Production seed endpoint');
    lines.push("  // Only available in non-production or when SCHEMOCK_ALLOW_SEED=true");
    lines.push("  if (process.env.NODE_ENV !== 'production' || process.env.SCHEMOCK_ALLOW_SEED === 'true') {");
    lines.push(`    router.post('${apiPrefix}/_seed', seedHandler.handler);`);
    lines.push('  }');
    lines.push('');
  }

  lines.push('  return router;');
  lines.push('}');
  lines.push('');

  // Export default configured router
  lines.push('/**');
  lines.push(' * Pre-configured router instance');
  lines.push(' * Use createRouter() for custom configuration');
  lines.push(' */');
  lines.push('export const router = createRouter();');

  return lines.join('\n');
}
