/**
 * React Context provider generator for API client injection
 *
 * This enables users to configure auth interceptors and use them
 * with the generated React Query hooks.
 *
 * @module cli/generators/provider
 * @category CLI
 */

import { CodeBuilder } from '../utils/code-builder';

/**
 * Generate React Context provider for API client injection
 *
 * @returns Generated TypeScript code
 */
export function generateProvider(): string {
  const code = new CodeBuilder();

  code.comment('GENERATED BY SCHEMOCK - DO NOT EDIT');
  code.line("import { createContext, useContext, type ReactNode } from 'react';");
  code.line("import { type ApiClient, api as defaultApi } from './client';");
  code.line();

  // Context
  code.multiDocComment([
    'React Context for the Schemock API client.',
    '',
    'This context provides the API client to all hooks in the component tree.',
    'By default, it uses the unconfigured `api` client.',
  ]);
  code.line('const SchemockContext = createContext<ApiClient>(defaultApi);');
  code.line();

  // Provider props type
  code.multiDocComment([
    'Props for the SchemockProvider component.',
  ]);
  code.block('export interface SchemockProviderProps {', () => {
    code.docComment('Optional configured API client. If not provided, uses the default unconfigured client.');
    code.line('client?: ApiClient;');
    code.docComment('Child components that will have access to the API client.');
    code.line('children: ReactNode;');
  });
  code.line();

  // Provider component
  code.multiDocComment([
    'Provider component for injecting a configured API client into hooks.',
    '',
    'Use this to provide an auth-configured client to all Schemock hooks.',
    '',
    '@example',
    '```tsx',
    "import { SchemockProvider, createClient } from './generated';",
    '',
    '// Create a client with auth interceptors',
    'const api = createClient({',
    '  onRequest: (ctx) => {',
    '    const token = localStorage.getItem("authToken");',
    '    if (token) {',
    '      ctx.headers.Authorization = `Bearer ${token}`;',
    '    }',
    '    return ctx;',
    '  },',
    '  onError: (error) => {',
    '    if (error.status === 401) {',
    '      window.location.href = "/login";',
    '    }',
    '  }',
    '});',
    '',
    '// Wrap your app with the provider',
    'function App() {',
    '  return (',
    '    <SchemockProvider client={api}>',
    '      <MyComponent />',
    '    </SchemockProvider>',
    '  );',
    '}',
    '',
    '// Now all hooks automatically use the configured client',
    'function MyComponent() {',
    '  const { data } = useUsers(); // Uses auth-configured client',
    '  return <div>{data?.data.map(u => u.name)}</div>;',
    '}',
    '```',
  ]);
  code.block('export function SchemockProvider({ client, children }: SchemockProviderProps): JSX.Element {', () => {
    code.line('return (');
    code.line('  <SchemockContext.Provider value={client ?? defaultApi}>');
    code.line('    {children}');
    code.line('  </SchemockContext.Provider>');
    code.line(');');
  });
  code.line();

  // Hook to access the client
  code.multiDocComment([
    'Hook to access the API client from context.',
    '',
    'This is used internally by generated hooks to access the configured client.',
    'You can also use it directly if you need to call API methods outside of hooks.',
    '',
    '@returns The API client from context (or default if no provider)',
    '',
    '@example',
    '```tsx',
    "import { useSchemockClient } from './generated';",
    '',
    'function MyComponent() {',
    '  const api = useSchemockClient();',
    '',
    '  const handleClick = async () => {',
    '    // Direct API call using the configured client',
    '    await api.user.create({ name: "John" });',
    '  };',
    '',
    '  return <button onClick={handleClick}>Create User</button>;',
    '}',
    '```',
  ]);
  code.block('export function useSchemockClient(): ApiClient {', () => {
    code.line('return useContext(SchemockContext);');
  });
  code.line();

  // Re-export types for convenience
  code.comment('Re-export client types for convenience');
  code.line("export type { ApiClient } from './client';");

  return code.toString();
}
