/**
 * README Generator for SQL Schema Documentation
 *
 * Generates comprehensive documentation for the generated SQL schema
 *
 * @module cli/generators/readme
 * @category CLI
 */

import type { AnalyzedSchema, GenerateSQLOptions } from '../types';
import { getSQLSummary } from './sql';
import { toSnakeCase } from '../utils/pluralize';

/**
 * Generate README documentation for the SQL schema
 */
export function generateReadme(
  schemas: AnalyzedSchema[],
  options: GenerateSQLOptions = {}
): string {
  const target = options.target ?? 'postgres';
  const summary = getSQLSummary(schemas);
  const lines: string[] = [];

  // Header
  lines.push('# Generated Database Schema');
  lines.push('');
  lines.push(`> Generated by Schemock on ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  // Overview
  lines.push('## Overview');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|--------|-------|');
  lines.push(`| Tables | ${summary.tables.length} |`);
  lines.push(`| Foreign Keys | ${summary.foreignKeys.length} |`);
  lines.push(`| Indexes | ${summary.indexes.length} |`);
  lines.push(`| RLS Policies | ${summary.rls.length * 4} |`);
  lines.push(`| RPC Functions | ${summary.functions.length} |`);
  lines.push('');

  // Tables section
  lines.push('## Tables');
  lines.push('');
  for (const table of summary.tables) {
    lines.push(`### ${table.name}`);
    lines.push('');
    lines.push(`- Columns: ${table.columns}`);
    lines.push(`- Timestamps: ${table.hasTimestamps ? 'Yes (created_at, updated_at)' : 'No'}`);
    lines.push(`- RLS Enabled: ${table.hasRLS ? 'Yes' : 'No'}`);
    lines.push('');
  }

  // Foreign Keys section
  if (summary.foreignKeys.length > 0) {
    lines.push('## Foreign Keys');
    lines.push('');
    lines.push('| Table | Column | References |');
    lines.push('|-------|--------|------------|');
    for (const fk of summary.foreignKeys) {
      lines.push(`| ${fk.table} | ${fk.column} | ${fk.references}(id) |`);
    }
    lines.push('');
  }

  // Indexes section
  if (summary.indexes.length > 0) {
    lines.push('## Indexes');
    lines.push('');
    lines.push('| Table | Index Name | Columns | Type | Unique | Auto |');
    lines.push('|-------|------------|---------|------|--------|------|');
    for (const idx of summary.indexes) {
      lines.push(`| ${idx.table} | ${idx.name} | ${idx.fields.join(', ')} | ${idx.type} | ${idx.unique ? 'Yes' : 'No'} | ${idx.autoGenerated ? 'Yes' : 'No'} |`);
    }
    lines.push('');
  }

  // RLS section
  if (summary.rls.length > 0) {
    lines.push('## Row-Level Security (RLS)');
    lines.push('');
    lines.push('### Enabled Tables');
    lines.push('');
    for (const rls of summary.rls) {
      lines.push(`#### ${rls.entity} (${rls.table})`);
      lines.push('');
      lines.push(`- Operations: ${rls.operations.join(', ')}`);
      if (rls.scope.length > 0) {
        lines.push(`- Scope: ${rls.scope.join(', ')}`);
      }
      if (rls.bypass.length > 0) {
        lines.push(`- Bypass: ${rls.bypass.join(', ')}`);
      }
      lines.push('');
    }

    // RLS context setup
    lines.push('### Setting RLS Context');
    lines.push('');
    lines.push('Before making queries, you must set the RLS context. The method depends on your platform:');
    lines.push('');

    if (target === 'supabase') {
      lines.push('#### Supabase');
      lines.push('');
      lines.push('Context is automatically extracted from JWT claims. Ensure your JWT includes:');
      lines.push('');
      const contextKeys = new Set<string>();
      for (const rls of summary.rls) {
        rls.scope.forEach((s) => {
          const match = s.match(/ctx\.(\w+)/);
          if (match) contextKeys.add(match[1]);
        });
        rls.bypass.forEach((b) => {
          const match = b.match(/ctx\.(\w+)/);
          if (match) contextKeys.add(match[1]);
        });
      }
      for (const key of contextKeys) {
        lines.push(`- \`${key}\``);
      }
      lines.push('');
      lines.push('```typescript');
      lines.push("import { createClient } from '@supabase/supabase-js';");
      lines.push('');
      lines.push('const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);');
      lines.push('');
      lines.push('// RLS is automatically applied based on the authenticated user');
      lines.push('const { data } = await supabase.from(\'posts\').select(\'*\');');
      lines.push('```');
    } else {
      lines.push('#### PostgreSQL / PGlite');
      lines.push('');
      lines.push('```sql');
      lines.push('-- Set context for the current transaction');
      lines.push("SET LOCAL app.user_id = 'your-user-uuid';");
      lines.push("SET LOCAL app.role = 'member';");
      lines.push("SET LOCAL app.team_id = 'your-team-uuid';");
      lines.push('');
      lines.push('-- Now queries are filtered by RLS');
      lines.push('SELECT * FROM posts;');
      lines.push('```');
    }
    lines.push('');

    lines.push('#### Application Code (Generated Client)');
    lines.push('');
    lines.push('```typescript');
    lines.push("import { setContext } from './generated/client';");
    lines.push('');
    lines.push('// Set context (typically from auth middleware)');
    lines.push('setContext({');
    lines.push("  userId: 'user-uuid-here',");
    lines.push("  role: 'member',");
    lines.push("  teamId: 'team-uuid-here',");
    lines.push('});');
    lines.push('');
    lines.push('// All subsequent queries are filtered by RLS');
    lines.push('const posts = await api.posts.findMany();');
    lines.push('```');
    lines.push('');
  }

  // RPC Functions section
  if (summary.functions.length > 0) {
    lines.push('## RPC Functions');
    lines.push('');
    for (const func of summary.functions) {
      lines.push(`### ${func.name}`);
      lines.push('');
      if (func.description) {
        lines.push(func.description);
        lines.push('');
      }
      lines.push('**Signature:**');
      lines.push('```sql');
      lines.push(`${toSnakeCase(func.name)}(${func.args}) -> ${func.returns}`);
      lines.push('```');
      lines.push('');
      lines.push('**Usage:**');
      lines.push('```sql');
      lines.push(`SELECT * FROM ${toSnakeCase(func.name)}(...);`);
      lines.push('```');
      lines.push('');
      if (target === 'supabase') {
        lines.push('```typescript');
        lines.push('// Via Supabase client');
        lines.push(`const { data } = await supabase.rpc('${toSnakeCase(func.name)}', { ... });`);
        lines.push('```');
        lines.push('');
      }
    }
  }

  // Middleware integration
  lines.push('## Middleware Integration');
  lines.push('');
  lines.push('### Express.js');
  lines.push('');
  lines.push('```typescript');
  lines.push("import { setContext } from './generated/client';");
  lines.push('');
  lines.push('// Middleware to set RLS context from authenticated user');
  lines.push('app.use((req, res, next) => {');
  lines.push('  const user = req.user; // From your auth middleware');
  lines.push('');
  lines.push('  setContext({');
  lines.push('    userId: user?.id ?? null,');
  lines.push("    role: user?.role ?? 'anonymous',");
  lines.push('    teamId: user?.teamId ?? null,');
  lines.push('  });');
  lines.push('');
  lines.push('  next();');
  lines.push('});');
  lines.push('```');
  lines.push('');

  lines.push('### Next.js API Routes');
  lines.push('');
  lines.push('```typescript');
  lines.push('// lib/with-rls.ts');
  lines.push("import { setContext } from '@/generated/client';");
  lines.push("import { getServerSession } from 'next-auth';");
  lines.push('');
  lines.push('export function withRLS(handler) {');
  lines.push('  return async (req, res) => {');
  lines.push('    const session = await getServerSession(req, res);');
  lines.push('');
  lines.push('    setContext({');
  lines.push('      userId: session?.user?.id ?? null,');
  lines.push("      role: session?.user?.role ?? 'anonymous',");
  lines.push('    });');
  lines.push('');
  lines.push('    return handler(req, res);');
  lines.push('  };');
  lines.push('}');
  lines.push('');
  lines.push('// pages/api/posts.ts');
  lines.push("import { withRLS } from '@/lib/with-rls';");
  lines.push('');
  lines.push('export default withRLS(async (req, res) => {');
  lines.push('  const posts = await api.posts.findMany();');
  lines.push('  res.json(posts);');
  lines.push('});');
  lines.push('```');
  lines.push('');

  lines.push('### Fastify');
  lines.push('');
  lines.push('```typescript');
  lines.push("import { setContext } from './generated/client';");
  lines.push('');
  lines.push("fastify.addHook('preHandler', async (request, reply) => {");
  lines.push('  const user = request.user;');
  lines.push('');
  lines.push('  setContext({');
  lines.push('    userId: user?.id ?? null,');
  lines.push("    role: user?.role ?? 'anonymous',");
  lines.push('  });');
  lines.push('});');
  lines.push('```');
  lines.push('');

  // Migration instructions
  lines.push('## Migration Instructions');
  lines.push('');
  lines.push('### Fresh Install');
  lines.push('');
  lines.push('```bash');
  lines.push('# Apply all migrations in order');
  lines.push('psql -d your_database -f sql/001_tables.sql');
  lines.push('psql -d your_database -f sql/002_foreign_keys.sql');
  lines.push('psql -d your_database -f sql/003_indexes.sql');
  lines.push('psql -d your_database -f sql/004_rls.sql');
  lines.push('psql -d your_database -f sql/005_functions.sql');
  lines.push('psql -d your_database -f sql/006_triggers.sql');
  lines.push('');
  lines.push('# Or use the combined file');
  lines.push('psql -d your_database -f sql/schema.sql');
  lines.push('```');
  lines.push('');

  if (target === 'supabase') {
    lines.push('### Supabase');
    lines.push('');
    lines.push('```bash');
    lines.push('# Create a new migration');
    lines.push('supabase migration new schema_setup');
    lines.push('');
    lines.push('# Copy contents of sql/schema.sql to the migration file');
    lines.push('# Then apply:');
    lines.push('supabase db push');
    lines.push('```');
    lines.push('');
  }

  lines.push('### PGlite (In-Browser)');
  lines.push('');
  lines.push('```typescript');
  lines.push("import { PGlite } from '@electric-sql/pglite';");
  lines.push("import schemaSQL from './sql/schema.sql?raw';");
  lines.push('');
  lines.push('const db = new PGlite();');
  lines.push('await db.exec(schemaSQL);');
  lines.push('```');
  lines.push('');

  // File structure
  lines.push('## Generated Files');
  lines.push('');
  lines.push('```');
  lines.push('sql/');
  lines.push('├── 001_tables.sql      # CREATE TABLE statements');
  lines.push('├── 002_foreign_keys.sql # Foreign key constraints');
  lines.push('├── 003_indexes.sql     # Index definitions');
  lines.push('├── 004_rls.sql         # Row-Level Security policies');
  lines.push('├── 005_functions.sql   # Stored procedures (RPC)');
  lines.push('├── 006_triggers.sql    # Update triggers');
  lines.push('├── schema.sql          # Combined single file');
  lines.push('└── README.md           # This documentation');
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}
